# includes
include(ExternalProject)

set(ENABLE_SHARED ${LEONARDO_SHARED_ALL})

list(APPEND RTC_OPTIONS "-DENABLE_SHARED=${ENABLE_SHARED}")

# message(STATUS "[${TOOLCHAIN_OPTIONS} ${COMMON_OPTIONS} ${RTC_OPTIONS}]")

ExternalProject_Add(RTC
    SOURCE_DIR ${CMAKE_SOURCE_DIR}/src/webrtc
    CMAKE_ARGS ${TOOLCHAIN_OPTIONS} ${COMMON_OPTIONS} ${RTC_OPTIONS}
)