# includes
include(ExternalProject)

set(USE_OPENSSL_PC OFF)
set(ENABLE_SHARED ${LEONARDO_SHARED_ALL})

list(APPEND RTMP_OPTIONS "-DENABLE_SHARED=${ENABLE_SHARED}")
list(APPEND RTMP_OPTIONS "-DUSE_OPENSSL_PC=${USE_OPENSSL_PC}")
list(APPEND RTMP_OPTIONS "-DLEONARDO_CRYPTO=${LEONARDO_CRYPTO}")

# message(STATUS "[${TOOLCHAIN_OPTIONS} ${COMMON_OPTIONS} ${RTMP_OPTIONS}]")

if(LEONARDO_CRYPTO)
    ExternalProject_Add(RTMP
        DEPENDS OPENSSL-EXTERNAL
        SOURCE_DIR ${CMAKE_SOURCE_DIR}/src/rtmp
        CMAKE_ARGS ${TOOLCHAIN_OPTIONS} ${COMMON_OPTIONS} ${RTMP_OPTIONS}
    )
else()
    ExternalProject_Add(RTMP
        SOURCE_DIR ${CMAKE_SOURCE_DIR}/src/rtmp
        CMAKE_ARGS ${TOOLCHAIN_OPTIONS} ${COMMON_OPTIONS} ${RTMP_OPTIONS}
    )
endif()