# includes
include(ExternalProject)

set(ENABLE_APPS OFF)
set(USE_OPENSSL_PC OFF)
set(ENABLE_HEAVY_LOGGING OFF)
set(ENABLE_ENCRYPTION ${LEONARDO_CRYPTO})
set(ENABLE_SHARED ${LEONARDO_SHARED_ALL})

list(APPEND SRT_OPTIONS "-DENABLE_SHARED=${ENABLE_SHARED}")
list(APPEND SRT_OPTIONS "-DENABLE_APPS=${ENABLE_APPS}")
list(APPEND SRT_OPTIONS "-DUSE_OPENSSL_PC=${USE_OPENSSL_PC}")
list(APPEND SRT_OPTIONS "-DENABLE_HEAVY_LOGGING=${ENABLE_HEAVY_LOGGING}")
list(APPEND SRT_OPTIONS "-DENABLE_ENCRYPTION=${ENABLE_ENCRYPTION}")

# message(STATUS "[${TOOLCHAIN_OPTIONS} ${COMMON_OPTIONS} ${SRT_OPTIONS}]")

if(LEONARDO_CRYPTO)
    ExternalProject_Add(SRT
        DEPENDS OPENSSL-EXTERNAL
        SOURCE_DIR ${CMAKE_SOURCE_DIR}/src/srt
        CMAKE_ARGS ${TOOLCHAIN_OPTIONS} ${COMMON_OPTIONS} ${SRT_OPTIONS}
    )
else()
    ExternalProject_Add(SRT
        SOURCE_DIR ${CMAKE_SOURCE_DIR}/src/srt
        CMAKE_ARGS ${TOOLCHAIN_OPTIONS} ${COMMON_OPTIONS} ${SRT_OPTIONS}
    )
endif()