
message(STATUS "LEONARDO_ARCH = ${LEONARDO_ARCH}")

if(LEONARDO_ARCH STREQUAL "x86")
    set(CMAKE_SYSTEM_NAME "Darwin")
    set(CMAKE_SYSTEM_PROCESSOR "i386")
    set(CMAKE_OSX_ARCHITECTURES "i386")
elseif(LEONARDO_ARCH STREQUAL "x86_64")
    set(CMAKE_SYSTEM_NAME "Darwin")
    set(CMAKE_SYSTEM_PROCESSOR "x86_64")
    set(CMAKE_OSX_ARCHITECTURES "x86_64")
else()
    message(FATAL_ERROR "Unknown LEONARDO_ARCH = [${LEONARDO_ARCH}]")
endif()

set(CMAKE_MACOSX_RPATH 1)

message(STATUS "CMAKE_HOST_SYSTEM_NAME = [${CMAKE_HOST_SYSTEM_NAME}]")
message(STATUS "CMAKE_SYSTEM_NAME = [${CMAKE_SYSTEM_NAME}]")
message(STATUS "CMAKE_SYSTEM_PROCESSOR = [${CMAKE_SYSTEM_PROCESSOR}]")
message(STATUS "CMAKE_OSX_ARCHITECTURES = [${CMAKE_OSX_ARCHITECTURES}]")

list(APPEND TOOLCHAIN_OPTIONS "-DCMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}")
list(APPEND TOOLCHAIN_OPTIONS "-DCMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}")
list(APPEND TOOLCHAIN_OPTIONS "-DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}")

set(OUT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/out/${CMAKE_OSX_ARCHITECTURES})

list(APPEND COMMON_OPTIONS "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}")
list(APPEND COMMON_OPTIONS "-DCMAKE_PREFIX_PATH=${OUT_DIR}")
list(APPEND COMMON_OPTIONS "-DCMAKE_INSTALL_PREFIX=${OUT_DIR}")

message(STATUS "OUT_DIR = ${OUT_DIR}")
message(STATUS "CMAKE_BUILD_TYPE = ${CMAKE_BUILD_TYPE}")
message(STATUS "CMAKE_PREFIX_PATH = ${CMAKE_PREFIX_PATH}")
message(STATUS "CMAKE_INSTALL_PREFIX = ${CMAKE_INSTALL_PREFIX}")