# =============================================================================
# macOS toolchain (64-bit only: arm64 / x86_64)
# =============================================================================

message(STATUS "LEONARDO_ARCH = ${LEONARDO_ARCH}")

set(LEONARDO_OSX_DEPLOYMENT_TARGET "11.0" CACHE STRING "macOS minimum deployment target")

if(LEONARDO_ARCH STREQUAL "x86_64")
    set(CMAKE_SYSTEM_NAME "Darwin")
    set(CMAKE_SYSTEM_PROCESSOR "x86_64")
    set(CMAKE_OSX_ARCHITECTURES "x86_64")
elseif(LEONARDO_ARCH STREQUAL "arm64")
    set(CMAKE_SYSTEM_NAME "Darwin")
    set(CMAKE_SYSTEM_PROCESSOR "arm64")
    set(CMAKE_OSX_ARCHITECTURES "arm64")
else()
    message(FATAL_ERROR
        "Unsupported LEONARDO_ARCH = [${LEONARDO_ARCH}]. "
        "64-bit only build supports: arm64, x86_64.")
endif()

set(CMAKE_OSX_DEPLOYMENT_TARGET ${LEONARDO_OSX_DEPLOYMENT_TARGET})
set(CMAKE_MACOSX_RPATH 1)

message(STATUS "CMAKE_HOST_SYSTEM_NAME     = [${CMAKE_HOST_SYSTEM_NAME}]")
message(STATUS "CMAKE_SYSTEM_NAME          = [${CMAKE_SYSTEM_NAME}]")
message(STATUS "CMAKE_SYSTEM_PROCESSOR     = [${CMAKE_SYSTEM_PROCESSOR}]")
message(STATUS "CMAKE_OSX_ARCHITECTURES    = [${CMAKE_OSX_ARCHITECTURES}]")
message(STATUS "CMAKE_OSX_DEPLOYMENT_TARGET= [${CMAKE_OSX_DEPLOYMENT_TARGET}]")

list(APPEND TOOLCHAIN_OPTIONS "-DCMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}")
list(APPEND TOOLCHAIN_OPTIONS "-DCMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}")
list(APPEND TOOLCHAIN_OPTIONS "-DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}")
list(APPEND TOOLCHAIN_OPTIONS "-DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}")

set(OUT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/out/${CMAKE_OSX_ARCHITECTURES})

list(APPEND COMMON_OPTIONS "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}")
list(APPEND COMMON_OPTIONS "-DCMAKE_PREFIX_PATH=${OUT_DIR}")
list(APPEND COMMON_OPTIONS "-DCMAKE_INSTALL_PREFIX=${OUT_DIR}")

message(STATUS "OUT_DIR              = ${OUT_DIR}")
message(STATUS "CMAKE_BUILD_TYPE     = ${CMAKE_BUILD_TYPE}")
