if(WIN32)
    message(STATUS "DETECTED SYSTEM: WINDOWS;")
elseif(ANDROID)
    message(STATUS "DETECTED SYSTEM: ANDROID;" )
elseif(IOS)
    message(STATUS "DETECTED SYSTEM: IOS;" )
elseif(APPLE)
    message(STATUS "DETECTED SYSTEM: APPLE;")
elseif(DARWIN)
    message(STATUS "DETECTED SYSTEM: DARWIN;")
elseif(BSD)
    message(STATUS "DETECTED SYSTEM: BSD;")
elseif(LINUX)
    message(STATUS "DETECTED SYSTEM: LINUX;" )
elseif(CYGWIN)
    message(STATUS "DETECTED SYSTEM: CYGWIN (posix mode);")
elseif(MSVC)
    message(STATUS "DETECTED SYSTEM: MSVC;")
else()
    message(FATAL_ERROR "Unsupported system: ${CMAKE_SYSTEM_NAME}")
endif()